### PR TITLE
Use Go's archive/zip to unzip repository archives

### LINKED ISSUE #109: Unzip failed with interactive message
**unzip version**: `UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.`
**OS**: `macOS Catalina 10.15.3`
Error log:

```
Unzipping the ZIP archive failed: unzip failed: exit status 1: replace /tmp/action-sd9-akita694954415/angular/playground/projects/ng-entity-service/src/lib/ng-entity-service-notifier.ts? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
```

```
# Repository github.com/sd9/akita @ refs/heads/master (1 steps)
# ERROR: Unzipping the ZIP archive failed: unzip failed: exit status 1: replace /tmp/action-sd9-akita391331449/angular/playground/projects/ng-entity-service/src/lib/ng-entity-service-notifier.ts? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
```

action file: 
```
{
  "scopeQuery": "repo:github.com/sd9/* repohasfile:^package.json",
  "steps": [
    {
      "type": "command",
      "args": ["sed", "-i", "", "s/\"main\"/\"es2015\"/", "package.json"]
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by mrnugget**
This fixes #109 by using Go's archive/zip package to unzip files.

(The code is taken from here and slightly modified: https://golangcode.com/unzip-files-in-go/)

It fixes the "interactive" problem, because it silently ignores
case-sensitive naming conflicts, which is what you get when using macOS'
Finder's unzip utility and unzip on the CLI. "Silently ignores" sounds
bad but I think it's what you expect to happen on macOS.

It also handles the chinese characters correctly.

@eseliger Can you test this with your repositories in #109?

### CODE REVIEW

File: cmd/src/actions_exec_backend_runner.go [hunk 1]
```diff
@@ -363,3 +359,50 @@ func repositoryZipArchiveURL(repoName, rev, token string) (*url.URL, error) {
...
+		if err != nil {
+			return err
+		}
+
+		rc, err := f.Open()
+		if err != nil {
+			return err
+		}
+
+		_, err = io.Copy(outFile, rc)
```
Comment (creachadair) [inline cmd/src/actions_exec_backend_runner.go]: We shouldn't ignore the error on closing `outFile`, since it's open for writing.

```go
_, err := io.Copy(outFile, rc)
rc.Close()
_, cerr := outFile.Close()
if err != nil {
  return err
} else if cerr != nil {
  return cerr
}
```

Otherwise we may silently drop data in uncommon-but-therefore-very-hard-to-debug cases.

Comment (mrnugget) [reply cmd/src/actions_exec_backend_runner.go]: Ahh, nice. Thank you!

File: cmd/src/actions_exec_backend_runner.go [hunk 2]
```diff
@@ -363,3 +359,50 @@ func repositoryZipArchiveURL(repoName, rev, token string) (*url.URL, error) {
...
+		}
+
+		outFile, err := os.OpenFile(fpath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, f.Mode())
+		if err != nil {
+			return err
+		}
+
+		rc, err := f.Open()
+		if err != nil {
+			return err
```
Comment (creachadair) [inline cmd/src/actions_exec_backend_runner.go]:
```suggestion
			outFile.Close()
			return err
```

To avoid orphaning a filehandle.

File: cmd/src/actions_exec_backend_runner.go [hunk 3]
```diff
@@ -363,3 +359,50 @@ func repositoryZipArchiveURL(repoName, rev, token string) (*url.URL, error) {
...
+		if !strings.HasPrefix(fpath, filepath.Clean(dest)+string(os.PathSeparator)) {
+			return fmt.Errorf("%s: illegal file path", fpath)
+		}
+
+		if f.FileInfo().IsDir() {
+			os.MkdirAll(fpath, os.ModePerm)
+			continue
+		}
+
+		if err = os.MkdirAll(filepath.Dir(fpath), os.ModePerm); err != nil {
```
Comment (creachadair) [inline cmd/src/actions_exec_backend_runner.go]:
```suggestion
		if err := os.MkdirAll(filepath.Dir(fpath), os.ModePerm); err != nil {
```

we don't really need to shadow here.

File: cmd/src/actions_exec_backend_runner.go [hunk 4]
```diff
@@ -363,3 +359,50 @@ func repositoryZipArchiveURL(repoName, rev, token string) (*url.URL, error) {
...
+	for _, f := range r.File {
+		fpath := filepath.Join(dest, f.Name)
+
+		// Check for ZipSlip. More Info: http://bit.ly/2MsjAWE
+		if !strings.HasPrefix(fpath, filepath.Clean(dest)+string(os.PathSeparator)) {
+			return fmt.Errorf("%s: illegal file path", fpath)
+		}
+
+		if f.FileInfo().IsDir() {
+			os.MkdirAll(fpath, os.ModePerm)
```
Comment (creachadair) [inline cmd/src/actions_exec_backend_runner.go]: We don't care if this fails?

**Comment by mrnugget** [comment]
@creachadair I've tried to address all of your feedback. Can you take another look? (Also: your thoroughness earned you a spot on my ask-for-review list 😎)

**Comment by eseliger** [comment]
fixes all reported nits from #109 :)

File: cmd/src/actions_exec_backend_runner.go [hunk 5]
```diff
@@ -363,3 +359,62 @@ func repositoryZipArchiveURL(repoName, rev, token string) (*url.URL, error) {
...
+	for _, f := range r.File {
+		fpath := filepath.Join(dest, f.Name)
+
+		// Check for ZipSlip. More Info: http://bit.ly/2MsjAWE
+		if !strings.HasPrefix(fpath, filepath.Clean(dest)+string(os.PathSeparator)) {
+			return fmt.Errorf("%s: illegal file path", fpath)
+		}
+
+		if f.FileInfo().IsDir() {
+			err := os.MkdirAll(fpath, os.ModePerm)
```
Comment (creachadair) [inline cmd/src/actions_exec_backend_runner.go]: This is of course fine as you wrote it, but I'd just one-line it as elsewhere:

```suggestion
			if err := os.MkdirAll(fpath, os.ModePerm); err != nil {
```

File: cmd/src/actions_exec_backend_runner.go [hunk 6]
```diff
@@ -363,3 +359,62 @@ func repositoryZipArchiveURL(repoName, rev, token string) (*url.URL, error) {
...
+	if err != nil {
+		return err
+	}
+	defer r.Close()
+
+	for _, f := range r.File {
+		fpath := filepath.Join(dest, f.Name)
+
+		// Check for ZipSlip. More Info: http://bit.ly/2MsjAWE
+		if !strings.HasPrefix(fpath, filepath.Clean(dest)+string(os.PathSeparator)) {
```
Comment (creachadair) [inline cmd/src/actions_exec_backend_runner.go]: I'd advise hoisting the prefix assembly out of the loop:

```go
outputBase := filepath.Clean(dest)+string(os.PathSeparator)
// …
if !strings.HasPrefix(fpath, outputBase) {
```

Not so much for performance but to be self-documenting.

File: cmd/src/actions_exec_backend_runner.go [hunk 7]
```diff
@@ -363,3 +359,62 @@ func repositoryZipArchiveURL(repoName, rev, token string) (*url.URL, error) {
...
+			return err
+		}
+
+		rc, err := f.Open()
+		if err != nil {
+			outFile.Close()
+			return err
+		}
+
+		if _, err = io.Copy(outFile, rc); err != nil {
```
Comment (creachadair) [inline cmd/src/actions_exec_backend_runner.go]: I would recommend doing this differently. As written, we're still missing a close of `outFile` if `rc.Close` fails. And we actually don't _care_ if closing `rc` fails, because it's only open for reading so there is no risk to data. At best we might want to log that.

What I would write here is:

```go
_, err := io.Copy(outFile, rc)
rc.Close()
_, cerr := outFile.Close()
// Now we have safely closed everything that needs it, and can check errors
if err != nil {
   return fmt.Errorf("copying %q: %v", f.Name, err)
}
if cerr != nil {
  return fmt.Errorf("closing: %v", cerr)
}
```

I know this pattern seems a little weird at first, but it's a lot easier to be sure we haven't missed a case if we do error checking as a separate phase. We _always_ want to close, regardless of what fails, and only after we've done that do we care whether something broke.

Comment (mrnugget) [reply cmd/src/actions_exec_backend_runner.go]: Ah, _now_ I get it. Thank you!

**Comment by mrnugget** [comment]
> What have I done? 😆

Don't worry, I appreciate it. "This is my jam", as they say :)
