### PR TITLE
batches: fix Docker Desktop for Linux handling

### LINKED ISSUE #754: batches: Docker Desktop for Linux: Invalid mount config for type "bind"
[Docker Desktop for Linux](https://docs.docker.com/desktop/linux/) is out and looks like it has similar problems to #405.

Somehow, the underlying dockerd cannot find the `-tmp` directory used to unpack repositories.

This happens whether `-workspace bind` or `-workspace volume`. Running in `-v` mode gives the following output:

``` console
sfllaw@hostname:~$ src batch preview -v -workspace volume -f batch-change.yaml 
✅ Parsing batch spec
✅ Resolving namespace
✅ Preparing container images  █████████████████████████████████████████████████
🚧 Workspace creator: volume
✅ Set workspace type
✅ Resolved 5 repositories
✅ Found 5 workspaces with steps to execute
✅ Found 4 cached changeset specs; 1 task needs to be executed
✅ Executing... (1/1, 1 errored)  ██████████████████████████████████████████████
│                                                                               
└── github.com/sfllaw/repo  creating workspace: preparing local g...  6s

❌ Error:
   github.com/sfllaw/repo:
   creating workspace: preparing local git repo: preparing workspace: Docker output:
   docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /tmp/src-run-1024304234.
   See 'docker run --help'.: exit status 125
   Log: /tmp/changeset-github.com-sfllaw-repo-service-2ee289175889fff0ee96efc10192185f8ed8c861.3212197002.log
```

I have since reverted to the system dockerd, which has no such problem.

### PR DESCRIPTION
**Pull request by LawnGnome**
If the default temporary directory is in use _and_ Docker Desktop for Linux is the default Docker context, this changes the temporary directory to be one under `~/.cache/sourcegraph/batch-tmp` instead.

Fixes #754.

### Test plan

Tested manually in both workspace modes.

### CODE REVIEW

**Review by eseliger — APPROVED** [review]
Nice!

**Review by Piszmog — APPROVED** [review]

File: internal/batches/docker/info.go [hunk 1]
```diff
@@ -10,6 +10,31 @@ import (
...
+// CurrentContext returns the name of the current Docker context (not to be
+// confused with a Go context).
+func CurrentContext(ctx context.Context) (string, error) {
+	dctx, cancel, err := withFastCommandContext(ctx)
+	if err != nil {
+		return "", err
+	}
+	defer cancel()
+
+	args := []string{"context", "inspect", "--format", "{{ .Name }}"}
```
Comment (courier-new) [inline internal/batches/docker/info.go:22]: Wow, it makes me happy that this is so straightforward to get from Docker! 😄

**Review by courier-new — APPROVED** [review]
I'm so glad you have an actual linux box to test this on. Thanks for all the comments for future context, too!

File: internal/batches/docker/info.go (hunk 1 above)
Comment (LawnGnome) [reply internal/batches/docker/info.go:22]: I suspected the hardest part of this ticket was going to be detecting this case, so this was a very pleasant surprise.
